---
###################################
# PACKAGES
###################################
- name: update package listings
  apt: update_cache=yes upgrade=no cache_valid_time=1800

- name: install nginx
  apt: pkg={{item}} state=latest
  with_items:
    nginx
  notify: restart nginx

# Enable nginx to start at boot.
- name: enable nginx
  service: name=nginx enabled=yes

# Configure nginx settings.
- name: configure nginx settings
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

