---
- name: deploy webservers
  hosts: webservers
  become: yes
  become_method: sudo
  roles:
    - common
    - nginx

- name: deploy loadbalancer
  hosts: lbservers
  become: yes
  become_method: sudo
  roles:
    - common
    - haproxy

