---
# This playbook refreshes local SSH key fingerprints, that keep changing when
# using Vagrant environments.
#
# To run the playbook on your localhost:
#   ansible-playbook localhost.yml
# Or to avoid any warnings:
#   ansible-playbook -i localhost.ini localhost.yml
#
# NOTE: this should be used only in a trusted local environment. Otherwise you
# may be making yourself vulnerable to MitM attacks.
#
# NOTE: this could now be simplified into a single task, but considering the
# iteration that went on this, simple is better than smart (and some nice tricks
# would be lost in the process as well).
#
- hosts: localhost
  gather_facts: no
  vars:
    known_hosts_file: "~/.ssh/known_hosts"
    target_subnet: "192.168.22."
    host_start: 50
    host_end: 59
  tasks:
    - name: Make sure the known hosts file exists
      file: "path={{ known_hosts_file }} state=touch"

    - name: Dummy task to build list of nodes for ssh fingerprint
      assert: { that: "'a' == 'a'" }
      with_sequence:
        start={{host_start}}
        end={{host_end}}
        format={{target_subnet}}%i
      register: target_hosts

    - name: Remove SSH fingerprints if they exist
      known_hosts:
        state=absent
        path="{{known_hosts_file}}"
        host="{{item}}"
      with_items: "{{ target_hosts.results | map(attribute='item') | list }}"

    - name: Add SSH fingerprints if the node is online
      known_hosts:
        state=present
        path="{{known_hosts_file}}"
        host="{{item}}"
        key="{{ lookup('pipe', 'ssh-keyscan -H -T 1 {{item}}') }}"
      with_items: "{{ target_hosts.results | map(attribute='item') | list }}"
      ignore_errors: yes


# vim:ft=ansible:

